-- Script generated by SimpleSpy - credits to exx#9394 211.771, 207.016, 608.796
local function Autobuygearshop(Itemname)
local Autogearshop = {
    [1] = "GearShop",
    [2] = Itemname
}

game.Players.LocalPlayer.Character.HumanoidRootPart.CFrame = CFrame.new(211.771, 207.016, 608.796)
task.wait(0.5)
game:GetService("ReplicatedStorage").RemoteEvents.PurchaseShopItem:InvokeServer(unpack(Autogearshop))
end